admin_app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("users/", views.UserList.as_view(), name="admin-users"),
    path("admin_workout_list/<int:user_id>", views.WorkoutList.as_view(), name="admin_workout_list"),
    path("admin_workout_exercise_list/<int:workout_id>/<int:user_id>", views.WorkoutExerciseList.as_view(), name="admin_workout_exercise_list"),
    path("admin_exercise_set_list/<int:workout_exercise_id>", views.ExerciseSetList.as_view(), name="admin_exercise_set_list"),
    path("admin_delete_user/<int:user_id>", views.DeleteUser.as_view(), name="admin_delete_user"),
    path("admin_exercise_list", views.ExerciseList.as_view(), name="admin_exercise_list"),
]

workout_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls,),
    path("", include("workout_app.urls"), name="workout-app-urls"),
    path("administration/", include("admin_app.urls"), name="admin-app-urls"),
    path('accounts/', include('allauth.urls')),    
]

admin_app/models.py
from django.db import models

workout_app/models.py
from django.db import models
from django.contrib.auth.models import User

# EXERCISE_TYPE is used in class Exercise
EXERCISE_TYPE = ((0, "Strength"), (1, "Cardio"))
# EXERCISE_GOAL is used in class Exercise
EXERCISE_GOAL = ((0, "Repetitions"), (2, "Distance"))

# A class for a Workout session
# A Wrokout is comprised of several sets.
# Each set is for one particular type of exercise
class Workout(models.Model):    
    # Relation to the user
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_workout")
    # Name of the session
    name = models.CharField(max_length=200, blank=False)
    # Date on which the workout took place
    date = models.DateTimeField(auto_now_add=True)
    # Meta for ordering the objects in a descending order
    class Meta:
        ordering = ['-date']
    # Strinbg representation of the object
    def __str__(self):
        return self.name

# A class for the type of exercise, such as push-ups, pull-ups, jogging, etc.
# The WorkoutSet class is related to this class. A WorkoutSet is for a particular
# type of exercise. For instance, the user wants to do a set of push-ups. 
class Exercise(models.Model): 
    # Relation to the user
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_exercise", default=1)   
    # Name of the exercise
    name = models.CharField(max_length=200, blank=False)
    # Type of exercise. There are only two types: Strength and Cardio which are
    # defined in a tupple at the top of this script file
    type = models.IntegerField(choices=EXERCISE_TYPE, default=0)
    # The goal field will only be used in conjunction with Exercises of type Cardio.
    # If the Exercise if of type Strength then this field will be left blank.
    # There are basicly two types of goal: distance and repetitions.
    goal = models.IntegerField(choices=EXERCISE_GOAL, default=0)
    # Strinbg representation of the object
    def __str__(self):
        return self.name

# This model is used to add exercises to a Workout
# Furthermore, ExerciseSets use it to add Sets of an Exercise in a workout
# In other words, this model is referenced as a ForeingKey by ExerciseSet
class WorkoutExercise(models.Model):
    # The relationshop to the owner object of type Workout
    workout= models.ForeignKey(
        Workout, on_delete=models.CASCADE, related_name="workout_workout_exercise")
    # The relationship to an Exercise object
    exercise = models.ForeignKey(Exercise, on_delete=models.PROTECT, related_name="exercise_workout_exercise")
    # Status of wether or not you're done with the exercise within the given workout
    done = models.BooleanField(default=False)
    # String representation of the object
    def __str__(self):
        return f"{self.workout.name} : {self.exercise.name}"


# A class for a set. It belongs to (related to) an object of type Workout.
# Each set must also be related to a particular exercise, such as pull-ups or jogging, etc.
class ExerciseSet(models.Model):
    # The relationshop to the owner object of type WorkoutExercise  
    workout_exercise = models.ForeignKey(WorkoutExercise, on_delete=models.CASCADE, related_name="workout_exercise_exercise_set", default=0)
    # Number of repetitioons in this set
    reps = models.IntegerField(blank=True, null=True, default="0")
    # The weight that was used, if weight lifting is involved
    weight = models.IntegerField(blank=True, null=True, default="0")
    # The time it took to complete the set, if it is a cardio exercise
    time = models.CharField(blank=True, null=True, default="00:00:00:0")
    # The distance covered in the ammount of time specified in the time field
    distance = models.FloatField(blank=True, null=True, default="0")
    def __str__(self):
        return f"{self.workout_exercise.__str__()}"

admin_app/forms.py
from django import forms


class CreateUserForm(forms.Form):
    # Form to create a User
    username = forms.CharField(label="Username:", max_length=100)
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput)

admin_app/views.py
from django.shortcuts import render, reverse
from django.views import View
from django.http import HttpResponseRedirect
from workout_app import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .forms import CreateUserForm
from django.db import IntegrityError
from django.contrib import messages
from django.core.paginator import Paginator


class UserList(View):
    # List of users. Also, creating and filtering users.
    template_name = "users.html"
    create_user_form_class = CreateUserForm
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        # Select all users
        User = get_user_model()
        users = User.objects.all()
        # Add users to the paginatro
        paginator = Paginator(users, self.paginate_by)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        # Create an empty form for creating users
        create_user_form = self.create_user_form_class()

        return render(request, self.template_name, {"page_obj": page_obj, "create_user_form": create_user_form})

    def post(self, request, *args, **kwargs):
        # Create user if a the according form has been submitted
        self.__create_user(request)
        # Copy the string that has been submitted in the search field
        # If it was empty the default value is an empty string, which will
        # yield all users
        seach_user = request.POST.get('search_user', "")
        # Instanciate an empty form to send back to the template
        create_user_form = self.create_user_form_class()
        # Select all users
        User = get_user_model()
        users = User.objects.all()
        # Create an empty list to hold filtered users
        user_list = []
        # Filter the users, according to the search_user value (The search-field on the page)
        for user in users:
            if seach_user in user.username:
                user_list.append(user)
        # Put the filtered results in the paginator
        paginator = Paginator(user_list, self.paginate_by)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {"page_obj": page_obj, "create_user_form": create_user_form})

    def __create_user(self, request):
        # Create a user if the create_user_form in home.html has been submitted
        create_user_form = self.create_user_form_class(request.POST)
        if create_user_form.is_valid():
            try:
                user_name = create_user_form.cleaned_data['username']
                password = create_user_form.cleaned_data['password1']
                User.objects.create_user(username=user_name,
                                         password=password)
            except IntegrityError:
                # This error will incur if the username already exists
                messages.add_message(
                    request, messages.ERROR, "The username already exists!")
        return


class WorkoutList(View):
    # List workouts by user.id
    template_name = "admin_workout_list.html"

    def get(self, request, *args, **kwargs):
        user_id = kwargs.get("user_id")
        user = User.objects.get(id=user_id)
        workout_list = models.Workout.objects.filter(
            user_id=user_id).order_by('id')
        return render(request, self.template_name, {"workout_list": workout_list, "user": user})


class WorkoutExerciseList(View):
    # List workout_exercises by workout.id
    template_name = "admin_workout_exercise_list.html"

    def get(self, request, *args, **kwargs):
        workout_id = kwargs.get("workout_id")
        user_id = kwargs.get("user_id")
        user = User.objects.get(id=user_id)

        workout_exercise_list = models.WorkoutExercise.objects.filter(
            workout_id=workout_id).order_by('id')
        return render(request, self.template_name, {"workout_exercise_list": workout_exercise_list, "user": user})


class ExerciseSetList(View):
    # List exercise_sets by workout_exercise.id
    template_name = "admin_exercise_set_list.html"

    def get(self, request, *args, **kwargs):
        workout_exercise_id = kwargs.get("workout_exercise_id")
        workout_exercise = models.WorkoutExercise.objects.get(
            id=workout_exercise_id)
        user = workout_exercise.workout.user  
        workout = workout_exercise.workout      
        exercise = workout_exercise.exercise
        exercise_set_list = models.ExerciseSet.objects.filter(
            workout_exercise_id=workout_exercise_id)
        return render(request, self.template_name, {"exercise_set_list": exercise_set_list, "exercise": exercise, "workout": workout, "user": user})


class DeleteUser(View):
    # Delete user
    def get(self, request, *args, **kwargs):
        user_id = kwargs.get("user_id")
        user = User.objects.get(id=user_id)
        user.delete()
        return HttpResponseRedirect(reverse('admin-users'))


class ExerciseList(View):
# List exercises and filter them by username
    template_name = "admin_exercise_list.html"
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        # All exercises
        exercise_list = models.Exercise.objects.all()
        # Empty list to hold filtered exercises
        exercises = [] 
        # In case there is no search_user in the session, make it an empty string
        search_user = ""
        if 'search_user' in request.session:
            search_user = request.session['search_user']
        
        # Filter the exercise list 
        for exercise in exercise_list:
            if search_user in exercise.user.username:
                exercises.append(exercise)
            elif search_user in exercise.name:                
                exercises.append(exercise)
        
        # Put the filtered results in the paginator
        paginator = Paginator(exercises, self.paginate_by)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(request, self.template_name, {"page_obj": page_obj, "search_user": search_user})

    def post(self, request, *args, **kwargs):
        exercise_list = models.Exercise.objects.all()
        # Copy the contents of the search field
        search_user = request.POST.get("search_user")
        # Copy the search_user from POST to session
        request.session['search_user'] = search_user
        # Create an empy list to hold the filtered exercise list
        exercises = []
        # Filter the exercise list 
        for exercise in exercise_list:
            if search_user in exercise.user.username:
                exercises.append(exercise)
            elif search_user in exercise.name:                
                exercises.append(exercise)
        
        # Put the filtered results in the paginator
        paginator = Paginator(exercises, self.paginate_by)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(request, self.template_name, {"page_obj": page_obj})

admin_app/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
        </script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <nav id="nav-bar">
        <ul class="navigation-menu">
            <li>
                <a class="nav-link active" aria-current="" page" href="{% url 'admin-users' %}"><i
                        class="fa-solid fa-users"></i>Users</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'admin_exercise_list' %}"><i
                    class="fa-solid fa-list"></i>Exercises</a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a class="nav-link" href="{% url 'account_logout' %}"><i
                        class="fa-solid fa-right-from-bracket"></i>Logout</a>
            </li>
            {% else %}
            <li>
                <a class="nav-link" href="{% url 'account_login' %}"><i
                        class="fa-solid fa-right-to-bracket"></i>Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    </header>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }} alert alert-dismissable fade show" {% endif %} id="msg"
            role="alert">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="" Close"></button>
    </div>
    {% endfor %}
    </div>
    {% endif %}
    {% block title %} {% endblock title %}

</head>

<body>
    {% block content %}

    {% endblock content %}
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <!-- Bootstrap js -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <!-- FONT AWSOME -->
    <script src="https://kit.fontawesome.com/73429b2bf2.js" crossorigin="anonymous"></script>
</body>

</html>

admin_app/templates/admin_exercise_list.html
{% extends "admin_base.html" %}

{% block title %}
<title>Exercises</title>
{% endblock title %}

{% block content %}
<h2>Filter by username or exercise name</h2>
<form method="POST">
    {% csrf_token %}
    <div class="container centered-text">
        <div class="row data-row">
            <div class="col-5 offset-2">
                <input id="search_user" type="text" class="input-field" name="search_user" value="{{ search_user }}" maxlength="50" placeholder="!Filter username or exercise name?">
            </div>
            <div class="col">
                <input type="submit" value="Go" class="wo-button" style="margin-top: 5px;">
            </div>
        </div>
    </div>
</form>
<h1>Exercises</h1>
<div class="container-fluid">
    <div class="row table-header">
        <div class="col">
            ID
        </div>
        <div class="col-5">
            Username
        </div>
        <div class="col">
            Exercise
        </div>
    </div>
    {% for exercise in page_obj %}

    <div class="row data-row">
        <div class="col">
            {{ exercise.id }}
        </div>
        <div class="col-5">
            {{ exercise.user.username }}
        </div>
        <div class="col">
            {{ exercise.name }}
        </div>
    </div>
    {% endfor %}
</div>
<div class="container">
    <div class="row">
        <div class="col-2">
            <!-- Placeholder -->
        </div>
        <div class="col-6 centered-text">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fa-solid fa-backward-fast"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-forward"></i></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa-solid fa-forward-fast"></i></a>
                    {% endif %}
                </span>
            </div>
        </div>
        <div class="col">
            <!-- Placeholder -->
        </div>
    </div>
</div>
{% endblock content %}

admin_app/templates/admin_exercise_set_list.html
{% extends "admin_base.html" %}

{% block content %}
<h1>Administration</h1>
<h3>{{ exercise.name }} </h3>
<div class="container-fluid">
{% for exercise_set in exercise_set_list %}
    <div class="row data-row">
        <div class="col">
            ID:
        </div>
        <div class="col">
            {{ exercise_set.id }}
        </div>
    </div>
    <div class="row data-row">
        <div class="col">
            Reps :
        </div>
        <div class="col">
            {{ exercise_set.reps }}
        </div>
    </div>
    <div class="row data-row">
        <div class="col">
            Weight :
        </div>
        <div class="col">
            {{ exercise_set.weight }}
        </div>
    </div>
    <div class="row data-row">
        <div class="col">
            Time :
        </div>
        <div class="col">
            {{ exercise_set.time }}
        </div>
    </div>
    <div class="row data-row">
        <div class="col">
            Distance :
        </div>
        <div class="col">
            {{ exercise_set.distance }}
        </div>
    </div>
    {% if forloop.last %} 
    <div class="row">
        <div class="col"> END OF SET </div>
    </div>
    {% else %} 
    <div class="row">
        <div class="col">
            NEXT SET 
        </div>
    </div>
    {% endif %}
    
{% endfor %}
</div>
<a href="{% url 'admin_workout_exercise_list' workout.id user.id %}" class="url-link centered-text" style="width:25%;">Back</a>
{% endblock content %}

admin_app/templates/admin_workout_exercise_list.html
{% extends "admin_base.html" %}

{% block content %}
<h1>Administration</h1>

<h3>Exercises in Workout of {{ user.username }}</h3>
{% for workout_exercise in workout_exercise_list %}

<div class="container-fluid">
    <div class="row data-row">
        <div class="col">
            {{ workout_exercise.id }}
        </div>
        <div class="col">
            <a href="{% url 'admin_exercise_set_list' workout_exercise.id %}" class="url-link">{{ workout_exercise.exercise.name }}</a>
        </div>        
    </div>
</div>

{% endfor %} 
<a href="{% url 'admin_workout_list' user.id %}" class="url-link centered-text" style="width:25%;">Back</a>
{% endblock content %}

admin_app/templates/admin_workout_list.html
{% extends "admin_base.html" %}

{% block content %}
<h1>Administration</h1>

<h3>Workouts of {{ user.username }}</h3>
{% for workout in workout_list %}

<div class="container-fluid">
    <div class="row data-row">
        <div class="col">
            {{ workout.id }}
        </div>
        <div class="col">
            <a href="{% url 'admin_workout_exercise_list' workout.id user.id %}" class="url-link">{{ workout.name }}</a>
        </div>        
    </div>
</div>

{% endfor %}
<a href="{% url 'admin-users' %}" class="url-link centered-text" style="width:25%;">Back</a>
{% endblock content %}

admin_app/templates/home.html
{% extends "admin_base.html" %}

{% block content %}
<h1>Administration</h1>
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <label for="search_user" class="data-row">Search:</label>
            </div>
            <div class="col-6">
                <input type="text" id="search_user" name="search_user" placeholder="!Enter string in a username!"
                    class="input-field">
            </div>
            <div class="col">
                <input type="submit" value="Go">
            </div>
        </div>
    </div>
</form>
<h2>Create User</h2>
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row data-row">
            <div class="col offset-2">
                Username:
            </div>
            <div class="col input-field">
                {{ create_user_form.username }}
            </div>            
        </div>
        <div class="row data-row">
            <div class="col offset-2">
                Password:
            </div>
            <div class="col input-field">
                {{ create_user_form.password1 }}
            </div>
        </div>
        <div class="row data-row">
            <div class="col offset-2">
                Confirm password:
            </div>
            <div class="col input-field">
                {{ create_user_form.password2 }}
            </div>
        </div>
        <div class="row data-row">
            <div class="col">
                <input type="submit" value="Create">
            </div>
        </div>
    </div>
    </div>
</form>
<h2>Users</h2>
{% for user in page_obj %}
<div class="container">
    <div class="row data-row">
        <div class="col-2 centered-text">
            {{ user.id }}
        </div>
        <div class="col-6 centered-text">
            <a href="{% url 'admin_workout_list' user.id %}" class="url-link">{{ user.username }}</a>
        </div>
        <div class="col centered-text">
            <a href="{% url 'admin_delete_user' user.id %}" class="url-link">Delete</a>
        </div>
    </div>
</div>
{% endfor %}
<div class="container">
    <div class="row">
        <div class="col-2">
            <!-- Placeholder -->
        </div>
        <div class="col-6 centered-text">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fa-solid fa-backward-fast"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-forward"></i></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa-solid fa-forward-fast"></i></a>
                    {% endif %}
                </span>
            </div>
        </div>
        <div class="col">
            <!-- Placeholder -->
        </div>
    </div>
</div>
{% endblock content %}

admin_app/templates/users.html
{% extends "admin_base.html" %}

{% block content %}
<h1>Administration</h1>
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <label for="search_user" class="data-row">Search:</label>
            </div>
            <div class="col-6">
                <input type="text" id="search_user" name="search_user" placeholder="!Enter string in a username!"
                    class="input-field">
            </div>
            <div class="col">
                <input type="submit" value="Go" class="wo-button" style="margin-top:5px;">
            </div>
        </div>
    </div>
</form>
<h2>Create User</h2>
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row data-row">
            <div class="col-2 offset-2">
                Username:
            </div>
            <div class="col input-field">
                {{ create_user_form.username }}
            </div>            
        </div>
        <div class="row data-row">
            <div class="col-2 offset-2">
                Password:
            </div>
            <div class="col input-field">
                {{ create_user_form.password1 }}
            </div>
        </div>
        <div class="row data-row">
            <div class="col-2 offset-2">
                Confirm password:
            </div>
            <div class="col input-field">
                {{ create_user_form.password2 }}
            </div>
        </div>
        <div class="row data-row">
            <div class="col-2 offset-2">
                <input type="submit" value="Create" class="wo-button">
            </div>
            <div class="col">
                <!-- Placeholder -->
            </div>
        </div>
    </div>
    </div>
</form>
<h2>Users</h2>
{% for user in page_obj %}
<div class="container">
    <div class="row data-row">
        <div class="col-2 centered-text">
            {{ user.id }}
        </div>
        <div class="col-6 centered-text">
            <a href="{% url 'admin_workout_list' user.id %}" class="url-link">{{ user.username }}</a>
        </div>
        <div class="col centered-text">
            <a class="url-link" href="#" data-bs-toggle="modal" data-bs-target="#modal{{user.id}}"><i
                class="fa-solid fa-trash-can"></i></a>
        </div>
    </div>
</div>
<!-- Modal Structure : Confirm Delete -->
<div id="modal{{user.id}}" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete {{ user.username }}?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Are you sure you want to delete {{ user.username }}?</h4>
                <p><i class="medium red material-icons">warning</i> <br>This action cannot be undone!
                </p>
            </div>
            <div class="modal-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'admin_delete_user' user.id %}"
                                class="url-link wo-button">Yes</a>
                        </div>
                        <div class="col">
                            <a href="#" class="wo-button url-link" data-bs-dismiss="modal">No</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <!-- Placehoder -->
    </div>
    <div class="col">
        <!-- Placehoder -->
    </div>
</div>
{% endfor %}
<div class="container">
    <div class="row">
        <div class="col-2">
            <!-- Placeholder -->
        </div>
        <div class="col-6 centered-text">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fa-solid fa-backward-fast"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-forward"></i></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa-solid fa-forward-fast"></i></a>
                    {% endif %}
                </span>
            </div>
        </div>
        <div class="col">
            <!-- Placeholder -->
        </div>
    </div>
</div>
{% endblock content %}